"""
lunara/codegen/triton_emitter.py
Walks a (post-pipeline) MLIR module and emits Triton Python kernel source.

Supported kernel types
──────────────────────
  • GEMM / MatMul      - tiled, double-buffered, with optional epilogue
  • Flash Attention    - forward pass (causal + non-causal)
  • Element-wise       - generic vectorised element-wise over arbitrary shapes
  • Fused Softmax      - online-normalisation softmax
  • Layer Norm         - two-pass (mean/var then normalise)
  • Conv2d             - im2col GEMM path

The emitter is deliberately source-level so generated code is readable,
debuggable, and easy to extend without recompiling C++.
"""

from __future__ import annotations

import math
import textwrap
from dataclasses import dataclass, field
from enum import Enum, auto
from pathlib import Path
from typing import List, Optional, Tuple

import triton          # noqa: F401 – imported for type hints; real use in exec
import triton.language as tl  # noqa: F401


# ─────────────────────────────────────────────────────────────────────────────
# Data model
# ─────────────────────────────────────────────────────────────────────────────

class KernelKind(Enum):
    GEMM        = auto()
    ATTENTION   = auto()
    ELEMENTWISE = auto()
    SOFTMAX     = auto()
    LAYERNORM   = auto()
    CONV2D      = auto()


@dataclass
class TileConfig:
    """Tile sizes and meta-parameters for a single kernel."""
    BLOCK_M: int = 128
    BLOCK_N: int = 128
    BLOCK_K: int = 32
    num_stages: int = 4        # software pipeline depth
    num_warps:  int = 4
    # For attention
    BLOCK_SEQ: int = 64
    HEAD_DIM:  int = 64
    # For element-wise
    BLOCK_SIZE: int = 1024


@dataclass
class KernelSpec:
    """Everything the emitter needs to generate one kernel."""
    kind:        KernelKind
    name:        str
    tile:        TileConfig = field(default_factory=TileConfig)
    dtype:       str = "float16"          # triton dtype string
    acc_dtype:   str = "float32"          # accumulator precision
    has_bias:    bool = False
    activation:  Optional[str] = None     # "relu" | "gelu" | "sigmoid" | None
    is_causal:   bool = False             # for attention
    num_heads:   int = 1
    epilogue_ops: List[str] = field(default_factory=list)


# ─────────────────────────────────────────────────────────────────────────────
# Source generation helpers
# ─────────────────────────────────────────────────────────────────────────────

def _indent(code: str, n: int = 4) -> str:
    return textwrap.indent(textwrap.dedent(code).strip(), " " * n)


def _activation_src(name: Optional[str], var: str = "acc") -> str:
    if name == "relu":
        return f"{var} = tl.maximum({var}, 0.0)"
    if name == "gelu":
        return (f"{var} = {var} * 0.5 * (1.0 + tl.math.erf({var} * 0.70710678))")
    if name == "sigmoid":
        return f"{var} = 1.0 / (1.0 + tl.math.exp(-{var}))"
    return ""


# ─────────────────────────────────────────────────────────────────────────────
# GEMM kernel
# ─────────────────────────────────────────────────────────────────────────────

_GEMM_TEMPLATE = '''\
"""
Auto-generated by Lunara codegen — GEMM kernel
  C[M,N] = A[M,K] @ B[K,N]  +  bias[N]?
  Tile: BLOCK_M={BLOCK_M}, BLOCK_N={BLOCK_N}, BLOCK_K={BLOCK_K}
  Stages: {num_stages}, Warps: {num_warps}
"""
import triton
import triton.language as tl


@triton.jit
def {name}(
    # Pointers
    A_ptr, B_ptr, C_ptr,
    {bias_arg}
    # Strides
    stride_am, stride_ak,
    stride_bk, stride_bn,
    stride_cm, stride_cn,
    # Shapes
    M, N, K,
    # Meta
    BLOCK_M: tl.constexpr,
    BLOCK_N: tl.constexpr,
    BLOCK_K: tl.constexpr,
):
    """Tiled GEMM with double-buffered software pipeline."""
    pid   = tl.program_id(axis=0)
    pid_m = pid  // tl.cdiv(N, BLOCK_N)
    pid_n = pid  %  tl.cdiv(N, BLOCK_N)

    rm = (pid_m * BLOCK_M + tl.arange(0, BLOCK_M)) % M
    rn = (pid_n * BLOCK_N + tl.arange(0, BLOCK_N)) % N
    rk = tl.arange(0, BLOCK_K)

    A = A_ptr + (rm[:, None] * stride_am + rk[None, :] * stride_ak)
    B = B_ptr + (rk[:, None] * stride_bk + rn[None, :] * stride_bn)

    acc = tl.zeros((BLOCK_M, BLOCK_N), dtype=tl.{acc_dtype})

    for k in tl.range(0, tl.cdiv(K, BLOCK_K), num_stages={num_stages}):
        mask_k = k * BLOCK_K + rk < K
        a = tl.load(A, mask=mask_k[None, :], other=0.0)
        b = tl.load(B, mask=mask_k[:, None], other=0.0)
        acc = tl.dot(a, b, acc, allow_tf32=True)
        A += BLOCK_K * stride_ak
        B += BLOCK_K * stride_bk

    acc = acc.to(tl.{dtype})
    {bias_load}
    {activation}

    mask_m = pid_m * BLOCK_M + tl.arange(0, BLOCK_M) < M
    mask_n = pid_n * BLOCK_N + tl.arange(0, BLOCK_N) < N
    C = C_ptr + (rm[:, None] * stride_cm + rn[None, :] * stride_cn)
    tl.store(C, acc, mask=mask_m[:, None] & mask_n[None, :])


def {name}_launch(A, B, C, bias=None):
    """Host-side launcher for {name}."""
    assert A.is_cuda and B.is_cuda and C.is_cuda
    M, K = A.shape
    K2, N = B.shape
    assert K == K2, f"Dimension mismatch: A{{M,{{K}}}} B{{{{K2}},{{N}}}}"

    grid = lambda meta: (triton.cdiv(M, meta["BLOCK_M"]) *
                         triton.cdiv(N, meta["BLOCK_N"]),)
    {name}[grid](
        A, B, C,
        {bias_launch}
        A.stride(0), A.stride(1),
        B.stride(0), B.stride(1),
        C.stride(0), C.stride(1),
        M, N, K,
        BLOCK_M={BLOCK_M}, BLOCK_N={BLOCK_N}, BLOCK_K={BLOCK_K},
        num_warps={num_warps}, num_stages={num_stages},
    )
    return C
'''


def emit_gemm(spec: KernelSpec) -> str:
    t = spec.tile
    bias_arg    = "bias_ptr," if spec.has_bias else ""
    bias_load   = (f"bias = tl.load(bias_ptr + rn, mask=mask_n, other=0.0)\n"
                   f"    acc += bias[None, :]") if spec.has_bias else ""
    bias_launch = "bias," if spec.has_bias else ""
    activation  = _activation_src(spec.activation, "acc")

    return _GEMM_TEMPLATE.format(
        name=spec.name,
        BLOCK_M=t.BLOCK_M, BLOCK_N=t.BLOCK_N, BLOCK_K=t.BLOCK_K,
        num_stages=t.num_stages, num_warps=t.num_warps,
        dtype=spec.dtype, acc_dtype=spec.acc_dtype,
        bias_arg=bias_arg, bias_load=bias_load, bias_launch=bias_launch,
        activation=activation,
    )


# ─────────────────────────────────────────────────────────────────────────────
# Flash Attention kernel (forward pass)
# ─────────────────────────────────────────────────────────────────────────────

_ATTN_TEMPLATE = '''\
"""
Auto-generated by Lunara — Flash Attention (forward)
  Causal: {is_causal}
  Head dim: {HEAD_DIM}, Block seq: {BLOCK_SEQ}
  Reference: Dao et al., FlashAttention-2 (2023)
"""
import triton
import triton.language as tl
import math


@triton.jit
def {name}(
    Q_ptr, K_ptr, V_ptr, Out_ptr,
    # Softmax scale (1/sqrt(d))
    sm_scale,
    # Strides: [batch, head, seq, dim]
    stride_qb, stride_qh, stride_qm, stride_qd,
    stride_kb, stride_kh, stride_kn, stride_kd,
    stride_vb, stride_vh, stride_vn, stride_vd,
    stride_ob, stride_oh, stride_om, stride_od,
    # Shapes
    B, H, M, N, D,
    BLOCK_M: tl.constexpr,
    BLOCK_N: tl.constexpr,
    HEAD_DIM: tl.constexpr,
    IS_CAUSAL: tl.constexpr,
):
    """
    Each program handles one (batch, head, BLOCK_M) tile of Q.
    Iterates over K/V in BLOCK_N chunks, accumulating softmax online.
    """
    start_m = tl.program_id(0)
    bh_idx  = tl.program_id(1)
    b_idx   = bh_idx  // H
    h_idx   = bh_idx  %  H

    q_off = b_idx * stride_qb + h_idx * stride_qh
    k_off = b_idx * stride_kb + h_idx * stride_kh
    v_off = b_idx * stride_vb + h_idx * stride_vh
    o_off = b_idx * stride_ob + h_idx * stride_oh

    Q_blk = Q_ptr + q_off + (start_m * BLOCK_M + tl.arange(0, BLOCK_M))[:, None] * stride_qm
    Q_blk = Q_blk + tl.arange(0, HEAD_DIM)[None, :] * stride_qd

    # Accumulators
    m_i = tl.full((BLOCK_M,), -1e9, dtype=tl.float32)
    l_i = tl.zeros((BLOCK_M,), dtype=tl.float32)
    acc = tl.zeros((BLOCK_M, HEAD_DIM), dtype=tl.float32)

    q = tl.load(Q_blk, mask=(start_m * BLOCK_M + tl.arange(0, BLOCK_M) < M)[:, None])

    lo = 0
    hi = (start_m + 1) * BLOCK_M if IS_CAUSAL else N

    for start_n in tl.range(lo, hi, BLOCK_N):
        rn = start_n + tl.arange(0, BLOCK_N)

        K_blk = K_ptr + k_off + rn[None, :] * stride_kn
        K_blk = K_blk + tl.arange(0, HEAD_DIM)[:, None] * stride_kd
        k = tl.load(K_blk, mask=(rn < N)[None, :], other=0.0)

        qk = tl.dot(q, k) * sm_scale  # (BLOCK_M, BLOCK_N)

        if IS_CAUSAL:
            row_idx = start_m * BLOCK_M + tl.arange(0, BLOCK_M)
            causal_mask = row_idx[:, None] >= rn[None, :]
            qk = tl.where(causal_mask, qk, -1e9)

        m_j = tl.max(qk, axis=1)
        p   = tl.math.exp(qk - m_j[:, None])
        l_j = tl.sum(p, axis=1)

        # Online softmax update
        m_new = tl.maximum(m_i, m_j)
        alpha = tl.math.exp(m_i - m_new)
        beta  = tl.math.exp(m_j - m_new)
        l_new = alpha * l_i + beta * l_j

        V_blk = V_ptr + v_off + rn[:, None] * stride_vn
        V_blk = V_blk + tl.arange(0, HEAD_DIM)[None, :] * stride_vd
        v = tl.load(V_blk, mask=(rn < N)[:, None], other=0.0)

        acc = acc * (alpha * l_i / l_new)[:, None] + tl.dot(p.to(tl.{dtype}), v) * (beta / l_new)[:, None]

        m_i = m_new
        l_i = l_new

    # Write output
    rm = start_m * BLOCK_M + tl.arange(0, BLOCK_M)
    O_blk = Out_ptr + o_off + rm[:, None] * stride_om
    O_blk = O_blk + tl.arange(0, HEAD_DIM)[None, :] * stride_od
    tl.store(O_blk, acc.to(tl.{dtype}), mask=(rm < M)[:, None])


def {name}_launch(Q, K, V, causal=False):
    """Host launcher for Flash Attention."""
    import torch
    B, H, M, D = Q.shape
    _, _, N, _ = K.shape
    Out = torch.empty_like(Q)
    sm_scale = 1.0 / math.sqrt(D)
    grid = (triton.cdiv(M, {BLOCK_SEQ}), B * H)
    {name}[grid](
        Q, K, V, Out,
        sm_scale,
        Q.stride(0), Q.stride(1), Q.stride(2), Q.stride(3),
        K.stride(0), K.stride(1), K.stride(2), K.stride(3),
        V.stride(0), V.stride(1), V.stride(2), V.stride(3),
        Out.stride(0), Out.stride(1), Out.stride(2), Out.stride(3),
        B, H, M, N, D,
        BLOCK_M={BLOCK_SEQ}, BLOCK_N={BLOCK_SEQ}, HEAD_DIM={HEAD_DIM},
        IS_CAUSAL=causal,
        num_warps={num_warps}, num_stages={num_stages},
    )
    return Out
'''


def emit_attention(spec: KernelSpec) -> str:
    t = spec.tile
    return _ATTN_TEMPLATE.format(
        name=spec.name,
        BLOCK_SEQ=t.BLOCK_SEQ, HEAD_DIM=t.HEAD_DIM,
        num_warps=t.num_warps, num_stages=t.num_stages,
        dtype=spec.dtype,
        is_causal=spec.is_causal,
    )


# ─────────────────────────────────────────────────────────────────────────────
# Fused Softmax kernel
# ─────────────────────────────────────────────────────────────────────────────

_SOFTMAX_TEMPLATE = '''\
"""Auto-generated by Lunara — Fused online Softmax"""
import triton
import triton.language as tl


@triton.jit
def {name}(X_ptr, Y_ptr, M, N,
            BLOCK: tl.constexpr):
    """One CTA per row; online max+sum in a single pass."""
    row = tl.program_id(0)
    cols = tl.arange(0, BLOCK)
    mask = cols < N
    x = tl.load(X_ptr + row * N + cols, mask=mask, other=-float("inf"))
    x_max = tl.max(x, axis=0)
    x_exp = tl.math.exp(x - x_max)
    x_sum = tl.sum(x_exp, axis=0)
    y = x_exp / x_sum
    tl.store(Y_ptr + row * N + cols, y, mask=mask)


def {name}_launch(X):
    import torch
    assert X.is_cuda
    M, N = X.shape
    Y = torch.empty_like(X)
    BLOCK = triton.next_power_of_2(N)
    {name}[(M,)](X, Y, M, N, BLOCK=BLOCK, num_warps={num_warps})
    return Y
'''


def emit_softmax(spec: KernelSpec) -> str:
    return _SOFTMAX_TEMPLATE.format(name=spec.name,
                                     num_warps=spec.tile.num_warps)


# ─────────────────────────────────────────────────────────────────────────────
# Layer Norm kernel
# ─────────────────────────────────────────────────────────────────────────────

_LAYERNORM_TEMPLATE = '''\
"""Auto-generated by Lunara — Layer Norm (two-pass)"""
import triton
import triton.language as tl


@triton.jit
def {name}(X_ptr, W_ptr, B_ptr, Y_ptr,
            N, eps,
            BLOCK: tl.constexpr):
    row  = tl.program_id(0)
    cols = tl.arange(0, BLOCK)
    mask = cols < N

    x = tl.load(X_ptr + row * N + cols, mask=mask, other=0.0).to(tl.float32)
    mean = tl.sum(x, axis=0) / N
    var  = tl.sum((x - mean) * (x - mean), axis=0) / N
    x_norm = (x - mean) / tl.math.sqrt(var + eps)

    w = tl.load(W_ptr + cols, mask=mask, other=1.0)
    b = tl.load(B_ptr + cols, mask=mask, other=0.0)
    y = x_norm * w + b
    tl.store(Y_ptr + row * N + cols, y.to(tl.{dtype}), mask=mask)


def {name}_launch(X, weight, bias, eps=1e-5):
    import torch
    assert X.is_cuda
    shape = X.shape
    X_2d = X.view(-1, shape[-1])
    M, N = X_2d.shape
    Y = torch.empty_like(X_2d)
    BLOCK = triton.next_power_of_2(N)
    {name}[(M,)](X_2d, weight, bias, Y, N, eps,
                  BLOCK=BLOCK, num_warps={num_warps})
    return Y.view(shape)
'''


def emit_layernorm(spec: KernelSpec) -> str:
    return _LAYERNORM_TEMPLATE.format(name=spec.name,
                                       num_warps=spec.tile.num_warps,
                                       dtype=spec.dtype)


# ─────────────────────────────────────────────────────────────────────────────
# Generic element-wise kernel
# ─────────────────────────────────────────────────────────────────────────────

_ELTWISE_TEMPLATE = '''\
"""Auto-generated by Lunara — Element-wise kernel"""
import triton
import triton.language as tl


@triton.jit
def {name}(X_ptr, Y_ptr, N,
            BLOCK: tl.constexpr):
    pid  = tl.program_id(0)
    offs = pid * BLOCK + tl.arange(0, BLOCK)
    mask = offs < N
    x = tl.load(X_ptr + offs, mask=mask)
    y = {body}
    tl.store(Y_ptr + offs, y, mask=mask)


def {name}_launch(X):
    import torch
    assert X.is_cuda
    N = X.numel()
    Y = torch.empty_like(X)
    grid = (triton.cdiv(N, {BLOCK_SIZE}),)
    {name}[grid](X, Y, N, BLOCK={BLOCK_SIZE}, num_warps={num_warps})
    return Y
'''

_ELTWISE_BODIES = {
    "relu":    "tl.maximum(x, 0.0)",
    "gelu":    "x * 0.5 * (1.0 + tl.math.erf(x * 0.70710678))",
    "sigmoid": "1.0 / (1.0 + tl.math.exp(-x))",
    "tanh":    "tl.math.tanh(x)",
    "identity":"x",
}


def emit_elementwise(spec: KernelSpec,
                     body: str = "tl.maximum(x, 0.0)") -> str:
    return _ELTWISE_TEMPLATE.format(
        name=spec.name,
        body=body,
        BLOCK_SIZE=spec.tile.BLOCK_SIZE,
        num_warps=spec.tile.num_warps,
    )


# ─────────────────────────────────────────────────────────────────────────────
# Main emitter entry-point
# ─────────────────────────────────────────────────────────────────────────────

class TritonEmitter:
    """
    Walks a list of KernelSpec objects and emits a single .py module
    containing all requested kernels plus a dispatch table.
    """

    def __init__(self, output_dir: str = "generated_kernels"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self._kernels: List[Tuple[str, str]] = []  # (name, source)

    def emit(self, spec: KernelSpec) -> str:
        """Generate source for one kernel; return source string."""
        dispatch = {
            KernelKind.GEMM:        emit_gemm,
            KernelKind.ATTENTION:   emit_attention,
            KernelKind.SOFTMAX:     emit_softmax,
            KernelKind.LAYERNORM:   emit_layernorm,
            KernelKind.ELEMENTWISE: emit_elementwise,
        }
        fn = dispatch.get(spec.kind)
        if fn is None:
            raise NotImplementedError(f"No emitter for {spec.kind}")
        src = fn(spec)
        self._kernels.append((spec.name, src))
        return src

    def write_module(self, module_name: str = "kernels") -> Path:
        """Write all emitted kernels into a single Python module."""
        header = (
            '"""Lunara auto-generated Triton kernels — DO NOT EDIT"""\n'
            "# fmt: off\n\n"
        )
        dispatch_table = "KERNEL_DISPATCH = {\n"
        sources = [header]
        for name, src in self._kernels:
            sources.append(src + "\n\n")
            dispatch_table += f'    "{name}": {name},\n'
        dispatch_table += "}\n"
        sources.append(dispatch_table)

        out_path = self.output_dir / f"{module_name}.py"
        out_path.write_text("\n".join(sources))
        print(f"[lunara] Wrote {len(self._kernels)} kernels → {out_path}")
        return out_path

    def write_individual(self) -> List[Path]:
        """Write each kernel as its own .py file."""
        paths = []
        for name, src in self._kernels:
            p = self.output_dir / f"{name}.py"
            p.write_text(src)
            paths.append(p)
        return paths


# ─────────────────────────────────────────────────────────────────────────────
# Convenience: emit a standard transformer block kernel set
# ─────────────────────────────────────────────────────────────────────────────

def emit_transformer_block(
    hidden_dim: int = 768,
    num_heads:  int = 12,
    seq_len:    int = 512,
    dtype:      str = "float16",
    output_dir: str = "generated_kernels",
) -> Path:
    """
    Emit the full kernel set for one transformer encoder block:
      qkv_proj (GEMM), attention (Flash), out_proj (GEMM),
      ffn1 (GEMM+GELU), ffn2 (GEMM), layer_norm x2.
    """
    head_dim   = hidden_dim // num_heads
    ffn_dim    = hidden_dim * 4
    tile_gemm  = TileConfig(BLOCK_M=128, BLOCK_N=128, BLOCK_K=32,
                             num_stages=4, num_warps=4)
    tile_attn  = TileConfig(BLOCK_SEQ=64, HEAD_DIM=head_dim,
                             num_stages=2, num_warps=4)

    emitter = TritonEmitter(output_dir)

    # QKV projection
    emitter.emit(KernelSpec("qkv_proj", KernelKind.GEMM,
                             tile_gemm, dtype=dtype, acc_dtype="float32"))
    # Flash Attention
    emitter.emit(KernelSpec("flash_attn", KernelKind.ATTENTION,
                             tile_attn, dtype=dtype, is_causal=False,
                             num_heads=num_heads))
    # Output projection
    emitter.emit(KernelSpec("out_proj", KernelKind.GEMM,
                             tile_gemm, dtype=dtype))
    # FFN layer 1 (with GELU)
    emitter.emit(KernelSpec("ffn1", KernelKind.GEMM, tile_gemm,
                             dtype=dtype, activation="gelu"))
    # FFN layer 2
    emitter.emit(KernelSpec("ffn2", KernelKind.GEMM, tile_gemm, dtype=dtype))
    # Layer norms
    for ln_name in ("layernorm_attn", "layernorm_ffn"):
        emitter.emit(KernelSpec(ln_name, KernelKind.LAYERNORM,
                                 TileConfig(num_warps=4), dtype=dtype))

    return emitter.write_module("transformer_block")


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Lunara Triton emitter")
    parser.add_argument("--hidden", type=int, default=768)
    parser.add_argument("--heads",  type=int, default=12)
    parser.add_argument("--seq",    type=int, default=512)
    parser.add_argument("--dtype",  default="float16")
    parser.add_argument("--out",    default="generated_kernels")
    args = parser.parse_args()
    path = emit_transformer_block(args.hidden, args.heads,
                                   args.seq, args.dtype, args.out)
    print(f"Generated: {path}")
